language: php

php:
  - '7.0'
  - nightly

services:
  - mongodb

env:
  global:
    - PATH="$HOME/bin:./vendor/bin:$PATH"

matrix:
  fast_finish: true
  include:
    - php: '7.0'
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: '7.0'
      env: MONGO_VERSION="latest"
    - php: hhvm
      env: COMPOSER_FLAGS="--prefer-lowest --ignore-platform-reqs"
    - php: hhvm
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
    - php: '7.0'
      env: SYMFONY=2.8.*
    - php: '7.0'
      env: SYMFONY=3.0.*
    - php: '7.0'
      env: SYMFONY=3.1.*
    - php: '7.0'
      env: SYMFONY=dev-master
  allow_failures:
    - php: hhvm
    - php: nightly
    - env: SYMFONY=dev-master

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi;
  - composer self-update
  - composer config --quiet --global github-oauth.github.com ${GITHUB_OAUTH_TOKEN}
  - if [ "$SYMFONY" != "" ]; then composer require "symfony/symfony:${SYMFONY}" --no-update; fi;

install:
  - if [ "$MONGO_VERSION" = "" ]; then pecl install -f mongodb-1.1.8; fi;
  - if [ "$MONGO_VERSION" = "latest" ]; then echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
  - mkdir --parents "${HOME}/bin"
  - composer update --prefer-dist --no-interaction ${COMPOSER_FLAGS}

before_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "zend_extension=xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;

script:
  - composer validate
  - phpunit -c . --coverage-clover=./build/coverage/coverage.clover

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar --output-document="${HOME}/bin/ocular" && chmod +x "${HOME}/bin/ocular"
  - ocular code-coverage:upload --format=php-clover ./build/coverage/coverage.clover

notifications:
  on_success: never
  on_failure: always
