version: "3.1"

services:

  php-cli:
    image: algatux/php-cli-mongodb:1.1
    volumes:
        - ./:/home/user-dev/project
    tty: true
    depends_on:
      - mongo
    container_name: mb_php

  mongo:
    image: mongo:3.4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPass
    container_name: mb_mongo

  webapp:
    image: ilariopierbattista/samplewebapp:1.0
    build:
      context: docker/webapp
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - ./webapp:/home/user-dev/webapp
      - ./src:/home/user-dev/webapp/mongodbbundle
    container_name: mb_webapp
    command: 'bin/console server:run 0.0.0.0:8000'
