version: "3.1"

services:
  php:
    image: ilariopierbattista/mongodb-bundle-php:${PHP_IMG}
    volumes:
        - ./:/home/user-dev/project
    tty: true
    depends_on:
      - mongo
    container_name: mb_php
  mongo:
    image: ${MONGO_IMG}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPass
    container_name: mb_mongo
    ports:
      - 27017:27017
