version: "3.1"

services:
  php:
    image: ilariopierbattista/mongodb-bundle-php:php-7.2-mongoext-1.5.3-20201126
    volumes:
        - ./:/home/user-dev/project
    tty: true
    depends_on:
      - mongo
      - mongo-noauth
    container_name: mb_php
  mongo:
    image: mongo:4.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPass
    container_name: mb_mongo

  mongo-noauth:
    image: mongo:4.0
    container_name: mb_mongo_noauth
