mongo_db_bundle:
  clients:
    sample_client:
      hosts:
        - { host: mongo, port: 27017 }
      username: root
      password: rootPass
      authSource: admin

  connections:
    default:
      client_name: sample_client
      database_name: sampledb
