mongo_db_bundle:
  clients:
    sample_client:
      hosts:
        - { host: localhost, port: 8080 }
      username: foo
      password: bar

  connections:
    default:
      client_name: sample_client
      database_name: sampledb
